name: Build and Push Docker Image to ECR

on:
  push:
    tags:
      - '*'  # Se ejecuta en cualquier tag

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Necesario si usas OIDC
    env:
      AWS_REGION: ${{ secrets.AWS_ECR_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ECR_ACCOUNT_ID }}
      REPO_NAME: ${{ secrets.AWS_ECR_REPO_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_ECR_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS \
              --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Extract tag
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          echo "Building image with tag: $TAG"
          IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$TAG
          docker build -t $IMAGE .
          docker push $IMAGE

          # Optional: tag and push as latest
          LATEST_IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:latest
          docker tag $IMAGE $LATEST_IMAGE
          docker push $LATEST_IMAGE
